name: 'packer - inspect'
description: 'Inspect the resources within a packer template'
inputs:
  template-path:
    description: 'Path to Packer Template'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.template-path }}
